/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\models\Astronaut.glb -o .\src\components\Astronaut.jsx -r public 
*/

import { Html, useAnimations, useGLTF } from "@react-three/drei";
import { useFrame, useGraph } from "@react-three/fiber";
import { useAtom } from "jotai";
import React, { useEffect, useMemo, useState } from "react";
import { SkeletonUtils } from "three-stdlib";
import { userAtom } from "./SocketManager";
import { useGrid } from "../../exoplanet-exploration-hooks/useGrid";

const MOVEMENT_SPEED = 0.075;

export function Astronaut({ id, ...props }) {
  const position = useMemo(() => props.position, []);
  const [path, setPath] = useState();
  const { gridToVector3 } = useGrid();

  useEffect(() => {
    const path = [];
    props.path?.forEach((gridPosition) => {
      path.push(gridToVector3(gridPosition));
    });
    setPath(path);
  }, [props.path]);
  const group = React.useRef();
  const { scene, animations } = useGLTF("/models/Astronaut.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);
  const [animation, setAnimation] = useState("CharacterArmature|Idle");

  useEffect(() => {
    actions[animation].reset().fadeIn(0.32).play();
    return () => actions[animation]?.fadeOut(0.32);
  }, [animation]);

  const [user] = useAtom(userAtom);

  useFrame((state) => {
    if (path?.length && group.current.position.distanceTo(path[0]) > 0.1) {
      const direction = group.current.position
        .clone()
        .sub(path[0])
        .normalize()
        .multiplyScalar(MOVEMENT_SPEED);
      group.current.position.sub(direction);
      group.current.lookAt(path[0]);
      setAnimation("CharacterArmature|Run");
    } else if (path?.length) {
      path.shift();
    } else {
      setAnimation("CharacterArmature|Idle");
    }
    if (id === user) {
      state.camera.position.x = group.current.position.x + 8;
      state.camera.position.y = group.current.position.y + 8;
      state.camera.position.z = group.current.position.z + 8;
      state.camera.lookAt(group.current.position);
    }
  });

  return (
    <group
      ref={group}
      {...props}
      position={position}
      dispose={null}
      name={`character-${id}`}
    >
      <group name="Root_Scene">
        <group name="RootNode">
          <group
            name="CharacterArmature"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <primitive object={nodes.Root} />
          </group>
          <group
            name="SpaceSuit_Feet"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <skinnedMesh
              name="SpaceSuit_Feet_1"
              geometry={nodes.SpaceSuit_Feet_1.geometry}
              material={materials.SciFi_Light_Accent}
              skeleton={nodes.SpaceSuit_Feet_1.skeleton}
            />
            <skinnedMesh
              name="SpaceSuit_Feet_2"
              geometry={nodes.SpaceSuit_Feet_2.geometry}
              material={materials.SciFi_Light}
              skeleton={nodes.SpaceSuit_Feet_2.skeleton}
            />
          </group>
          <group
            name="SpaceSuit_Legs"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <skinnedMesh
              name="SpaceSuit_Legs_1"
              geometry={nodes.SpaceSuit_Legs_1.geometry}
              material={materials.SciFi_Light_Accent}
              skeleton={nodes.SpaceSuit_Legs_1.skeleton}
            />
            <skinnedMesh
              name="SpaceSuit_Legs_2"
              geometry={nodes.SpaceSuit_Legs_2.geometry}
              material={materials.SciFi_Light}
              skeleton={nodes.SpaceSuit_Legs_2.skeleton}
            />
            <skinnedMesh
              name="SpaceSuit_Legs_3"
              geometry={nodes.SpaceSuit_Legs_3.geometry}
              material={materials.SciFi_MainDark}
              skeleton={nodes.SpaceSuit_Legs_3.skeleton}
            />
            <skinnedMesh
              name="SpaceSuit_Legs_4"
              geometry={nodes.SpaceSuit_Legs_4.geometry}
              material={materials.SciFi_Main}
              skeleton={nodes.SpaceSuit_Legs_4.skeleton}
            />
          </group>
          <group
            name="SpaceSuit_Body"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <skinnedMesh
              name="SpaceSuit_Body_1"
              geometry={nodes.SpaceSuit_Body_1.geometry}
              material={materials.SciFi_Light_Accent}
              skeleton={nodes.SpaceSuit_Body_1.skeleton}
            />
            <skinnedMesh
              name="SpaceSuit_Body_2"
              geometry={nodes.SpaceSuit_Body_2.geometry}
              material={materials.SciFi_Light}
              skeleton={nodes.SpaceSuit_Body_2.skeleton}
            />
            <skinnedMesh
              name="SpaceSuit_Body_3"
              geometry={nodes.SpaceSuit_Body_3.geometry}
              material={materials.SciFi_MainDark}
              skeleton={nodes.SpaceSuit_Body_3.skeleton}
            />
            <skinnedMesh
              name="SpaceSuit_Body_4"
              geometry={nodes.SpaceSuit_Body_4.geometry}
              material={materials.SciFi_Main}
              skeleton={nodes.SpaceSuit_Body_4.skeleton}
            />
          </group>
          <group
            name="SpaceSuit_Head"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <skinnedMesh
              name="SpaceSuit_Head_1"
              geometry={nodes.SpaceSuit_Head_1.geometry}
              material={materials.SciFi_Light_Accent}
              skeleton={nodes.SpaceSuit_Head_1.skeleton}
            />
            <skinnedMesh
              name="SpaceSuit_Head_2"
              geometry={nodes.SpaceSuit_Head_2.geometry}
              material={materials.SciFi_Light}
              skeleton={nodes.SpaceSuit_Head_2.skeleton}
            />
            <skinnedMesh
              name="SpaceSuit_Head_3"
              geometry={nodes.SpaceSuit_Head_3.geometry}
              material={materials.Grey}
              skeleton={nodes.SpaceSuit_Head_3.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/Astronaut.glb");
